### ISSUE TITLE
Demo App is not showing UI in android 6.0 and 8.0 tested in LG nexus and MI

### ISSUE THREAD

**Issue by VikasSinghaiAndroid** [flipkart-incubator/proteus#114]
Hi,

Some how i managed to keep the demo apk generation and project setup in android studio 3.0,
1. Demo app is not showing the UI with available json files in RAW folder in the demo app i used performance, app is not crashing but UI is not coming it is just showing white blank screen.
2. I installed the node js and hosted data folder then i used demo app and changed the base url to hosted url butn first i got recycle view error so i commented recycle view after that app is not crashing but again it is not showing UI just showing black white screen with floating bar button.

Thank you!

**Comment by VikasSinghaiAndroid** [comment]
com.flipkart.android.proteus.exceptions.ProteusInflateException: attribute  'children' must be an array of 'Layout' objects

**Comment by VikasSinghaiAndroid** [comment]
FATAL EXCEPTION: main
                                                                                   Process: proteus.com.proteussample, PID: 6655
                                                                                   java.lang.NoSuchMethodError: No virtual method createDataContext(Lcom/flipkart/android/proteus/ProteusContext;Lcom/flipkart/android/proteus/value/Layout;Lcom/flipkart/android/proteus/value/ObjectValue;Landroid/view/ViewGroup;I)Lcom/flipkart/android/proteus/DataContext; in class Lcom/flipkart/android/proteus/support/v7/widget/RecyclerViewParser; or its super classes (declaration of 'com.flipkart.android.proteus.support.v7.widget.RecyclerViewParser' appears in /data/app/proteus.com.proteussample-1/split_lib_slice_5_apk.apk)
                                                                                       at com.flipkart.android.proteus.support.v7.widget.RecyclerViewParser.createViewManager(RecyclerViewParser.java:91)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.createViewManager(SimpleLayoutInflater.java:164)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:89)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser.handleChildren(ViewGroupParser.java:167)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:130)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:122)
                                                                                       at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:128)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:178)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:191)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:105)
                                                                                       at com.flipkart.android.proteus.parser.IncludeParser.createView(IncludeParser.java:77)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.createView(SimpleLayoutInflater.java:159)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:77)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser.handleChildren(ViewGroupParser.java:167)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:130)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:122)
                                                                                       at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:128)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:178)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:191)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:105)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser.handleChildren(ViewGroupParser.java:167)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:130)
                                                                                       at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:122)
                                                                                       at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:128)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:178)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
                                                                                       at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:191)
                                                                                       at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:105)
                                                                                       at proteus.com.proteussample.ProteusActivity.render(ProteusActivity.java:245)
                                                                                       at proteus.com.proteussample.ProteusActivity$7.onPostExecute(ProteusActivity.java:314)
                                                                                       at proteus.com.proteussample.ProteusActivity$7.onPostExecute(ProteusActivity.java:286)
                                                                                       at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
04-29 00:23:22.933 6655-6655/proteus.com.proteussample E/AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by adityasharat** [comment]
Acknowledged. Will check it out. 
@VikasSinghaiAndroid Can you please confirm if debug variant is working correctly?

**Comment by VikasSinghaiAndroid** [comment]
Hi Aditya,

I have taken Main and performance code base from Git demo app to my sample app and added all the lib by keeping library source code from git  into libs folder of the app and then added in project after that only i was able to run the demo code base, git demo project is not compiling because of that i need to create separate sample project for demo, but i used demo source code only for the same.
But no luck for the UI.
I am trying to achieve very basic requirement using Proteus lib  : 
1. Load the view with one single button, onClick of that button it should open a dialog, dialog will have another button, onClick of that dialog i need to open another activity [View].

Aditya, do you feel this is feasible using Proteus lib. If yes, Is it possible to get any sample for the same.

Thank you!

**Comment by VikasSinghaiAndroid** [comment]
Hi Aditya,

I am using debug build variant only, no luck.

Thank you!

**Comment by adityasharat** [comment]
> is feasible using Proteus lib?

Yes, is feasible using Proteus! You will have to implement the handling of the dialog and click listeners (i.e. logic) but you can inflate views with proteus.

Regarding building the demo project I just tried to build the `master` branch on `Android Studio 3.1.2` without updating the gradle build version (which is `2.3.3`); it was successfully compiled.

The demo also ran successfully using the `debug` flavor (not `performance`)

![screen shot 2018-04-30 at 10 27 30](https://user-images.githubusercontent.com/1552857/39415546-3cb9a7e2-4c62-11e8-80a4-fef82d9f835f.png)

![screenshot_1525064187](https://user-images.githubusercontent.com/1552857/39415549-4173600c-4c62-11e8-8a51-968b08b7c8a6.png)

If you are still facing problems it is likely because of some changes you have made or other environment variables. Please share the stacktrace of the compile error and other variables.

Also please ask questions on [SO](https://stackoverflow.com/questions/tagged/proteus)

**Comment by VikasSinghaiAndroid** [comment]
Hi Aditya,

Thank you very much for very very quick reply, i am just doing the same as suggest by you.
I hosted in http://192.168.1.4:8080/data

Will let you know as soon as i get the result.

Thank you!

**Comment by VikasSinghaiAndroid** [comment]
Hi Aditya,

It is working amazing earlier i updated gradle build version because of that it cause the issue.

Aditya, i am not finding any sample code for onClick event in the demo application, which i can refer for my requirements.

Thank you!

**Comment by VikasSinghaiAndroid** [comment]
I am refereeing https://github.com/flipkart-incubator/proteus/issues/70
https://github.com/flipkart-incubator/proteus/wiki/Layout-Builder-Callback

**Comment by VikasSinghaiAndroid** [comment]
I got this {
                  "type": "ImageView",
                  "layout_width": "@dimen/sixty",
                  "layout_height": "@dimen/sixty",
                  "src": "@drawable/github_icon",
                  "onClick": {
                    "someKey": "someValue"
                  }

In the demo app 👍 

Thank you!

**Comment by adityasharat** [comment]
Closing this in favor of #115
