### ISSUE TITLE
Failed to invoke public com.flipkart.android.proteus.value.Value() with no args

### ISSUE THREAD

**Issue by poovarasanvasudevan** [flipkart-incubator/proteus#129]
Hi 
I am getting Exception on parsing Styles here is my kotlin code, I kept my styles json in assets
```
styles = Gson().fromJson(BaseApplication.context.readJSONFromAsset("styles") , Styles::class.java )
```

and styles
```
{
  "money": {
    "textColor": "#56a411",
    "textSize": "28sp"
  },
  "center": {
    "layout_gravity": "center"
  },
  "mini": {
    "textSize": "8sp",
    "layout_width": "wrap_content",
    "layout_height": "wrap_content",
    "layout_margin": "4dp"
  },
  "blue": {
    "textColor": "#027cd5"
  },
  "default": {
    "textColor": "#323232",
    "textSize": "14sp"
  }
}
```

and Exception i am getting
```
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err: java.lang.RuntimeException: Failed to invoke public com.flipkart.android.proteus.value.Value() with no args
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:888)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:853)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:802)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:774)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.caretech.servicefocus.activity.FormActivity.START(FormActivity.kt:86)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.caretech.servicefocus.core.BaseActivity.DO_OPERTATION(BaseActivity.kt:67)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.caretech.servicefocus.core.BaseActivity.onCreate(BaseActivity.kt:60)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.caretech.servicefocus.activity.FormActivity.onCreate(FormActivity.kt:121)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.os.Looper.loop(Looper.java:154)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err: Caused by: java.lang.InstantiationException: Can't instantiate abstract class com.flipkart.android.proteus.value.Value
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
2018-11-30 18:55:46.858 15814-15814/com.caretech.servicefocus W/System.err: 	... 27 more

```

**Comment by adityasharat** [comment]
The exception is thrown because the `gson` instance is using the `ReflectiveTypeAdapterFactory` to deserialize `Styles`. Which will fail because `Value` is an abstract class.

_Inferred from:_
```
2018-11-30 18:55:46.857 15814-15814/com.caretech.servicefocus W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
```

You are creating a new instance of `Gson` for deserializing `Styles` and this instance of does not register with `ProteusTypeAdapterFactory` which is required for deserializing proteus components.

_Inferred from:_
```
styles = Gson().fromJson(...)
```

Use the same instance of `Gson` which is being used to deserialize `Layout`; which registers `ProteusTypeAdapterFactory`.

see:

1. [How to register the type adapter](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/DemoApplication.java#L45-L48)
2. [How to set proteus instance on the type adapter](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/api/ProteusManager.java#L57-L67)

**Comment by adityasharat** [comment]
Closing.
