### ISSUE TITLE
demo app fatal exception: MAIN

### ISSUE THREAD

**Issue by mgood7123** [flipkart-incubator/proteus#138]
Android Pie 9.0
Samsung S8 G950F
HadesRom
```
03/02 14:44:25: Launching demo
$ adb install-multiple -r -t /home/AndroidStudioProjects/proteus/demo/build/intermediates/resources/instant-run/debug/resources-debug.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/dep/dependencies.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_1.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_0.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_2.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_3.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_4.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_5.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_6.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_7.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_8.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/split-apk/debug/slices/slice_9.apk /home/AndroidStudioProjects/proteus/demo/build/intermediates/instant-run-apk/debug/demo-debug.apk 
Split APKs installed in 4 s 498 ms
$ adb shell am start -n "com.flipkart.android.proteus.demo/com.flipkart.android.proteus.demo.ProteusActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 25229 on device samsung-sm_n950f-ce091829e258a11b04
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/Zygote: isWhitelistProcess - Process is Whitelisted
E/Zygote: accessInfo : 1
I/id.proteus.dem: Late-enabling -Xcheck:jni
W/id.proteus.dem: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10262(com.flipkart.android.proteus.demo) identical 10 lines
W/id.proteus.dem: JIT profile information will not be recorded: profile file does not exits.
W/GraphicsEnvironment: driver package 'com.samsung.gpudriver.N8MaliG71_90' not installed
I/InstantRun: starting instant run server: is main process
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/vndksupport: Loading /vendor/lib64/egl/libGLES_mali.so from current namespace instead of sphal namespace.
D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
I/DecorView: createDecorCaptionView >> DecorView@b9bb699[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
W/id.proteus.dem: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/id.proteus.dem: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/OpenGLRenderer: Skia GL Pipeline
D/EmergencyMode: [EmergencyManager] android createPackageContext successful
E/DataLoaderTask: ERROR: CLEARTEXT communication not supported: [ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true)]
D/InputTransport: Input channel constructed: fd=76
D/ViewRootImpl@4b95dfb[ProteusActivity]: setView = DecorView@b9bb699[ProteusActivity] TM=true MM=false
W/Activity: AppLock checkAppLockState locked:false verifying:false pkgName = com.flipkart.android.proteus.demo isInMultiWindowMode:false showWhenLocked:false
D/ViewRootImpl@4b95dfb[ProteusActivity]: dispatchAttachedToWindow
D/ViewRootImpl@4b95dfb[ProteusActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x7 surface={valid=true 498389340160} changed=true
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: eglCreateWindowSurface = 0x73f21a8d00, 0x740a51d010
D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/ViewRootImpl@4b95dfb[ProteusActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b9bb699[ProteusActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b9bb699[ProteusActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.flipkart.android.proteus.demo ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=86
D/InputTransport: Input channel constructed: fd=88
D/ViewRootImpl@8122eea[Toast]: setView = android.widget.LinearLayout{d0575db V.E...... ......I. 0,0-0,0} TM=true MM=false
V/Toast: Text: DLEA in android.widget.Toast$TN@79e1878
D/ViewRootImpl@8122eea[Toast]: dispatchAttachedToWindow
D/ViewRootImpl@8122eea[Toast]: Relayout returned: old=[0,84][1440,2792] new=[115,212][1324,2568] result=0x7 surface={valid=true 497702543360} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: eglCreateWindowSurface = 0x73f1c88d00, 0x73e1622010
D/ViewRootImpl@4b95dfb[ProteusActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b9bb699[ProteusActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.flipkart.android.proteus.demo ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
D/ViewRootImpl@8122eea[Toast]: MSG_RESIZED_REPORT: frame=Rect(115, 212 - 1324, 2568) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@4b95dfb[ProteusActivity]: ViewPostIme key 0
D/ViewRootImpl@4b95dfb[ProteusActivity]: ViewPostIme key 1
D/ViewRootImpl@4b95dfb[ProteusActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b9bb699[ProteusActivity]
    getNavigationBarColor() -855310
D/InputTransport: Input channel destroyed: fd=86
W/libEGL: EGLNativeWindowType 0x740a51d010 disconnect failed
D/OpenGLRenderer: eglDestroySurface = 0x73f21a8d00, 0x740a51d000
D/ViewRootImpl@4b95dfb[ProteusActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@4b95dfb[ProteusActivity]: setWindowStopped(true) old=false
D/ViewRootImpl@4b95dfb[ProteusActivity]: Surface release. android.view.WindowManagerGlobal.setStoppedState:669 android.app.Activity.performStop:7647 android.app.ActivityThread.callActivityOnStop:4373 android.app.ActivityThread.performStopActivityInner:4351 android.app.ActivityThread.handleStopActivity:4426 android.app.servertransaction.TransactionExecutor.performLifecycleSequence:192 android.app.servertransaction.TransactionExecutor.cycleToPath:165 android.app.servertransaction.TransactionExecutor.executeLifecycleState:142 
D/ViewRootImpl@4b95dfb[ProteusActivity]: dispatchDetachedFromWindow
    Surface release. android.view.ViewRootImpl.doDie:7944 android.view.ViewRootImpl.die:7912 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4748 android.app.servertransaction.DestroyActivityItem.execute:39 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 
D/InputTransport: Input channel destroyed: fd=76
W/libEGL: EGLNativeWindowType 0x73e1622010 disconnect failed
D/OpenGLRenderer: eglDestroySurface = 0x73f1c88d00, 0x73e1622000
D/ViewRootImpl@8122eea[Toast]: dispatchDetachedFromWindow
D/ViewRootImpl@8122eea[Toast]: Surface release. android.view.ViewRootImpl.doDie:7944 android.view.ViewRootImpl.die:7912 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.widget.Toast$TN.handleHide:1158 android.widget.Toast$TN$1.handleMessage:946 android.os.Handler.dispatchMessage:106 
D/InputTransport: Input channel destroyed: fd=88
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@7263af
I/DecorView: createDecorCaptionView >> DecorView@b048fa8[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
E/DataLoaderTask: ERROR: CLEARTEXT communication not supported: [ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true)]
D/InputTransport: Input channel constructed: fd=84
D/ViewRootImpl@52db774[ProteusActivity]: setView = DecorView@b048fa8[ProteusActivity] TM=true MM=false
W/Activity: AppLock checkAppLockState locked:false verifying:false pkgName = com.flipkart.android.proteus.demo isInMultiWindowMode:false showWhenLocked:false
D/ViewRootImpl@52db774[ProteusActivity]: dispatchAttachedToWindow
D/ViewRootImpl@52db774[ProteusActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x7 surface={valid=true 497702543360} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: eglCreateWindowSurface = 0x73f21a8300, 0x73e1622010
D/InputTransport: Input channel constructed: fd=88
D/ViewRootImpl@5eea1f8[Toast]: setView = android.widget.LinearLayout{9c4b6d1 V.E...... ......I. 0,0-0,0} TM=true MM=false
V/Toast: Text: DLEA in android.widget.Toast$TN@f1bb536
D/ViewRootImpl@5eea1f8[Toast]: dispatchAttachedToWindow
D/ViewRootImpl@5eea1f8[Toast]: Relayout returned: old=[0,84][1440,2792] new=[115,212][1324,2568] result=0x7 surface={valid=true 497980825600} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: eglCreateWindowSurface = 0x73f21a8d00, 0x73f1f86010
D/ViewRootImpl@52db774[ProteusActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b048fa8[ProteusActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@b048fa8[ProteusActivity]
D/InputMethodManager: getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.flipkart.android.proteus.demo ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=91
D/ViewRootImpl@52db774[ProteusActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
D/ViewRootImpl@5eea1f8[Toast]: MSG_RESIZED_REPORT: frame=Rect(115, 212 - 1324, 2568) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@5eea1f8[Toast]: ViewPostIme pointer 0
W/libEGL: EGLNativeWindowType 0x73f1f86010 disconnect failed
D/OpenGLRenderer: eglDestroySurface = 0x73f21a8d00, 0x73f1f86000
D/ViewRootImpl@5eea1f8[Toast]: dispatchDetachedFromWindow
D/ViewRootImpl@5eea1f8[Toast]: Surface release. android.view.ViewRootImpl.doDie:7944 android.view.ViewRootImpl.die:7912 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.widget.Toast$TN.handleHide:1158 android.widget.Toast$TN$1.handleMessage:953 android.os.Handler.dispatchMessage:106 
D/InputTransport: Input channel destroyed: fd=88
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 0
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 1
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 0
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 1
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 0
D/ViewRootImpl@52db774[ProteusActivity]: ViewPostIme pointer 1
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flipkart.android.proteus.demo, PID: 25229
    com.flipkart.android.proteus.exceptions.ProteusInflateException: layout : 'AlertDialogLayout' not found
        at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:126)
        at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:140)
        at com.flipkart.android.proteus.demo.ProteusActivity.alert(ProteusActivity.java:194)
        at com.flipkart.android.proteus.demo.ProteusActivity.access$000(ProteusActivity.java:51)
        at com.flipkart.android.proteus.demo.ProteusActivity$5.onClick(ProteusActivity.java:130)
        at android.view.View.performClick(View.java:7352)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27801)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
I/Process: Sending signal. PID: 25229 SIG: 9
Application terminated.
```

**Comment by adityasharat** [comment]
I was able to successfully run the project

Android Studio version:

```
Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 28, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

Emulator version

```
Android version: 7.0
```

Could you share the Android Studio version, and emulator version. In addition I would urge you to try a fresh checkout and make sure that the server is running.

**Comment by mgood7123** [comment]
> 
> 
> I was able to successfully run the project
> 
> Android Studio version:
> 
> ```
> Android Studio 3.3.1
> Build #AI-182.5107.16.33.5264788, built on January 28, 2019
> JRE: 1.8.0_152-release-1248-b01 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.2
> ```
> 
> Emulator version
> 
> ```
> Android version: 7.0
> ```
> 
> Could you share the Android Studio version, and emulator version. In addition I would urge you to try a fresh checkout and make sure that the server is running.

sais the person that just posts his description in the TITLE tab instead of the DESCRIPTION tab ._.

**Comment by adityasharat** [comment]
Without more details it will be difficult to help. Especially since the build succeeds locally as well as on [travis](https://travis-ci.org/flipkart-incubator/proteus). Closing this issue.

**Comment by elugoti** [comment]
Right now server is not running, for alternative solution you can do one thing, go to github/firebase and upload files which are in project code, and change endpoint like this "https://raw.githubusercontent.com/END_POINT_TO_JSON_FILE"
